/**
 * `dsh-enterprise init` — port of facility/packages/cli/src/init.mjs as TS.
 * @module @deepseek-ai/dsh-enterprise-cli/init
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { execSync } from 'node:child_process'
function renderIitConfigYaml(cfg: { minPhi: number; max_exact_size: number; tpmVars: string[] }): string {
  return [
    '# DSH Enterprise IIT config — generated by dsh-enterprise init',
    `# minPhi: minimum integrated information threshold`,
    `minPhi: ${cfg.minPhi}`,
    `max_exact_size: ${cfg.max_exact_size}`,
    `tpmVars:`,
    ...cfg.tpmVars.map((v) => `  - ${v}`),
  ].join('\n') + '\n'
}
const DEFAULT_CONFIG = { minPhi: 0.1, max_exact_size: 15, tpmVars: ['tool_success', 'approval_granted', 'skill_loaded', 'sandbox_ok'] }

const BEGIN = '<!-- BEGIN dsh-enterprise -->'
const END = '<!-- END dsh-enterprise -->'

function hasManagedBlock(content: string): boolean {
  return content.includes(BEGIN) && content.includes(END)
}

function appendManagedBlock(content: string, block: string): string {
  if (hasManagedBlock(content)) return content
  const trimmed = content.endsWith('\n') ? content : content + '\n'
  return `${trimmed}\n${block}\n`
}

function managedBlock(): string {
  return [
    BEGIN,
    '## DSH Enterprise',
    '',
    'Managed by `dsh-enterprise init`. Do not edit between markers.',
    '- Profile: enterprise',
    '- IIT config: `.dsh/iit-config.yaml`',
    '- Workflows: `.github/workflows/{plan,build,review}.yml`',
    END,
  ].join('\n')
}

function detectPackageManager(dir: string): string {
  if (existsSync(join(dir, 'pnpm-workspace.yaml')) || existsSync(join(dir, 'pnpm-lock.yaml'))) return 'pnpm'
  if (existsSync(join(dir, 'yarn.lock'))) return 'yarn'
  if (existsSync(join(dir, 'package-lock.json'))) return 'npm'
  return 'pnpm'
}

function detectDefaultBranch(dir: string): string {
  try {
    const out = execSync('git config --get init.defaultBranch 2>/dev/null || git branch --show-current 2>/dev/null || echo main', { cwd: dir, encoding: 'utf8' }).trim()
    return out.split('\n')[0]?.trim() || 'main'
  } catch { return 'main' }
}

function workflowStub(name: string, branch: string): string {
  // minimal header mirroring facility/.github workflow headers
  return [
    `name: ${name}`,
    `on:`,
    `  push:`,
    `    branches: [${branch}]`,
    `  pull_request:`,
    `    branches: [${branch}]`,
    `jobs:`,
    `  ${name}:`,
    `    runs-on: ubuntu-latest`,
    `    steps:`,
    `      - uses: actions/checkout@v4`,
    `      - run: echo "dsh-enterprise ${name} stub — replace with real workflow"`,
    ``,
  ].join('\n')
}

export type InitOpts = {
  dir?: string
  with?: string[]
  without?: string[]
  force?: boolean
}

export async function runInit(opts: InitOpts = {}): Promise<void> {
  const dir = opts.dir ?? process.cwd()
  const withSet = new Set((opts.with ?? []).map(s => s.trim()).filter(Boolean))
  const withoutSet = new Set((opts.without ?? []).map(s => s.trim()).filter(Boolean))

  const includeIitGuards = !withoutSet.has('iit-guards') && (withSet.size === 0 || withSet.has('iit-guards'))
  const includeWatchtower = !withoutSet.has('watchtower')

  // --with filtering: if --with is specified, only include those listed
  // (except always include base). Handle generically: if withSet non-empty, only those in withSet are included.
  // For now two optional features: iit-guards, watchtower
  const wantIit = withSet.size === 0 ? includeIitGuards : withSet.has('iit-guards')
  const wantWatchtower = withSet.size === 0 ? includeWatchtower : withSet.has('watchtower')

  const pm = detectPackageManager(dir)
  void pm
  const branch = detectDefaultBranch(dir)

  // .dsh.json
  const dshJsonPath = join(dir, '.dsh.json')
  if (!existsSync(dshJsonPath) || opts.force) {
    writeFileSync(dshJsonPath, JSON.stringify({ profile: 'enterprise' }, null, 2) + '\n')
  }

  // .dsh/iit-config.yaml
  if (wantIit) {
    const dshDir = join(dir, '.dsh')
    mkdirSync(dshDir, { recursive: true })
    const cfgPath = join(dshDir, 'iit-config.yaml')
    if (!existsSync(cfgPath) || opts.force) {
      const yaml = renderIitConfigYaml(DEFAULT_CONFIG)
      writeFileSync(cfgPath, yaml)
    }
  }

  // .github/workflows/{plan,build,review}.yml stubs
  const wfDir = join(dir, '.github/workflows')
  mkdirSync(wfDir, { recursive: true })
  for (const name of ['plan', 'build', 'review'] as const) {
    const p = join(wfDir, `${name}.yml`)
    if (!existsSync(p) || opts.force) {
      writeFileSync(p, workflowStub(name, branch))
    }
  }

  // AGENTS.md / CLAUDE.md managed blocks
  const block = managedBlock()
  for (const entry of ['AGENTS.md', 'CLAUDE.md'] as const) {
    const target = join(dir, entry)
    if (!existsSync(target)) {
      const header = entry === 'CLAUDE.md' ? `Follow AGENTS.md.\n\n${block}\n` : `# Agent instructions\n\n${block}\n`
      writeFileSync(target, header)
    } else {
      const content = readFileSync(target, 'utf8')
      if (!hasManagedBlock(content)) {
        writeFileSync(target, appendManagedBlock(content, block))
      }
    }
  }

  // install skills/guards stub copy — create guards dir with placeholder
  if (wantWatchtower || wantIit) {
    const guardsDir = join(dir, 'guards')
    mkdirSync(guardsDir, { recursive: true })
    const guardPlaceholder = join(guardsDir, 'README.md')
    if (!existsSync(guardPlaceholder)) {
      writeFileSync(guardPlaceholder, '# Guards\n\nManaged by dsh-enterprise. See `.dsh/iit-config.yaml`.\n')
    }
  }
}

export { hasManagedBlock, appendManagedBlock, managedBlock }
