/**
 * IIT guard runner config.
 * @module @deepseek-ai/dsh-enterprise-guards-iit/config
 */

export interface CausalEmergenceConfig {
  minEffectiveness: number
  maxDegeneracy: number
}

export interface PhiTrajectoryConfig {
  window: number
  maxDrop: number
  maxSlope: number
}

export interface MipShiftConfig {
  window: number
  maxShift: number
}

export interface BoundaryFrontierConfig {
  minBoundaryPhi: number
}

export interface EffectEthosConfig {
  teloidsYaml: string
  severity: 'error' | 'warn'
}

export interface Config {
  minPhi: number
  max_exact_size: number
  tpmVars: string[]
  causalEmergence: CausalEmergenceConfig
  phiTrajectory: PhiTrajectoryConfig
  mipShift: MipShiftConfig
  boundaryFrontier: BoundaryFrontierConfig
  effectEthos: EffectEthosConfig
}

export const DEFAULT_CONFIG: Config = {
  minPhi: 0.1,
  max_exact_size: 15,
  tpmVars: ['tool_success', 'approval_granted', 'skill_loaded', 'sandbox_ok'],
  causalEmergence: { minEffectiveness: 0.1, maxDegeneracy: 0.9 },
  phiTrajectory: { window: 10, maxDrop: 0.15, maxSlope: -0.02 },
  mipShift: { window: 10, maxShift: 2.0 },
  boundaryFrontier: { minBoundaryPhi: 0.1 },
  effectEthos: { teloidsYaml: '', severity: 'warn' },
}

export function renderIitConfigYaml(cfg: Config): string {
  return [
    '# DSH Enterprise IIT config — generated by dsh-enterprise init',
    `# minPhi: minimum integrated information threshold`,
    `minPhi: ${cfg.minPhi}`,
    `max_exact_size: ${cfg.max_exact_size}`,
    `tpmVars:`,
    ...cfg.tpmVars.map((v: string) => `  - ${v}`),
  ].join('\n') + '\n'
}
