/**
 * IIT guard runner config — zod schema + .dsh/iit-config.yaml writer.
 * @module @deepseek-ai/dsh-enterprise-guards-iit/config
 */

import z from '@deepseek-ai/schemastery'

export const Config = z.object({
  minPhi: z.number().default(0.1),
  max_exact_size: z.number().default(15),
  tpmVars: z.array(z.string()).default(['tool_success', 'approval_granted', 'skill_loaded', 'sandbox_ok']),

  // P0 guard configs — per-guard threshold overrides
  causalEmergence: z.object({
    minEffectiveness: z.number().default(0.1),
    maxDegeneracy: z.number().default(0.9),
  }).default({ minEffectiveness: 0.1, maxDegeneracy: 0.9 }),
  phiTrajectory: z.object({
    window: z.number().default(10),
    maxDrop: z.number().default(0.15),
    maxSlope: z.number().default(-0.02),
    viabilityWarn: z.number().default(-0.5),
    viabilityBlock: z.number().default(-0.8),
  }).default({ window: 10, maxDrop: 0.15, maxSlope: -0.02, viabilityWarn: -0.5, viabilityBlock: -0.8 }),
  mipShift: z.object({
    window: z.number().default(10),
    maxShift: z.number().default(2.0),
  }).default({ window: 10, maxShift: 2.0 }),
  boundaryFrontier: z.object({
    minBoundaryPhi: z.number().default(0.1),
  }).default({ minBoundaryPhi: 0.1 }),
  effectEthos: z.object({
    teloidsYaml: z.string().default(''),
    severity: z.union(['error', 'warn']).default('warn'),
  }).default({ teloidsYaml: '', severity: 'warn' }),
})

export type Config = ReturnType<typeof Config.parse>

/**
 * YAML schema written to `.dsh/iit-config.yaml` on `dsh-enterprise init`.
 * Kept as string for scaffold without adding a yaml dep at runtime.
 */
export function renderIitConfigYaml(cfg: Config): string {
  return [
    '# DSH Enterprise IIT config — generated by dsh-enterprise init',
    `# minPhi: minimum integrated information threshold`,
    `minPhi: ${cfg.minPhi}`,
    `max_exact_size: ${cfg.max_exact_size}`,
    `tpmVars:`,
    ...cfg.tpmVars.map((v: string) => `  - ${v}`),
  ].join('\n') + '\n'
}

/** Default config (parsed with defaults applied). */
export const DEFAULT_CONFIG: Config = Config.parse({})
