/**
 * IIT guard runner config — zod schema + .dsh/iit-config.yaml writer.
 * @module @deepseek-ai/dsh-enterprise-guards-iit/config
 */

import z from '@deepseek-ai/schemastery'

export const Config = z.object({
  minPhi: z.number().default(0.1),
  max_exact_size: z.number().default(15),
  tpmVars: z.array(z.string()).default(['tool_success', 'approval_granted', 'skill_loaded', 'sandbox_ok']),
})

export type Config = {
  minPhi: number
  max_exact_size: number
  tpmVars: string[]
}

/**
 * YAML schema written to `.dsh/iit-config.yaml` on `dsh-enterprise init`.
 * Kept as string for scaffold without adding a yaml dep at runtime.
 */
export function renderIitConfigYaml(cfg: Config): string {
  return [
    '# DSH Enterprise IIT config — generated by dsh-enterprise init',
    `# minPhi: minimum integrated information threshold`,
    `minPhi: ${cfg.minPhi}`,
    `max_exact_size: ${cfg.max_exact_size}`,
    `tpmVars:`,
    ...cfg.tpmVars.map((v) => `  - ${v}`),
  ].join('\n') + '\n'
}

/** Default config (parsed with defaults applied). */
export const DEFAULT_CONFIG: Config = Config({} as Config) as Config
